version: "3.9"

services:
  dynamic-cell-culture-drive-db:
    image: timescale/timescaledb:latest-pg16
    container_name: dynamic-cell-culture-drive-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dynamic-cell-culture-drive-db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}" ]
      timeout: 2s
      retries: 2
    networks:
      - dynamic-cell-culture-drive-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: dynamic-cell-culture-drive-db
    privileged: true
    depends_on:
      - dynamic-cell-culture-drive-db
    volumes:
      - ./backend:/app
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - dynamic-cell-culture-drive-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - dynamic-cell-culture-drive-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

volumes:
  dynamic-cell-culture-drive-db_data:
    name: dynamic-cell-culture-drive-db_data

networks:
  dynamic-cell-culture-drive-network:
    driver: bridge
